### ISSUE TITLE
Externalizable config for a chain

### ISSUE THREAD

**Issue by splix** [ethereumproject/go-ethereum#131]
A json or yaml config for a chain.

I propose following structure:
```
# id of a chain
id: main 
# human readable name for chain
name: Mainnet 
genesis:
  block:
    nonce: 0x0000000000000042
    mixHash: 0x0000000000000000000000000000000000000000000000000000000000000000
    difficulty: 0x400000000"
    author: 0x0000000000000000000000000000000000000000
    timestamp: 0
    extraData: 0x11bbe8db4e347b4e8c937c1c8370e4b5ed33adb3db69cbdb7a38e1e50b1b82fa
    gasLimit: 0x1388
    stateRoot: 0xd7f8974fb5ac78d9ac099b9ad5018bedc2ce0a72dad1827a1709da30580f0544
  gasprice: olympic # id of gas prices table for evm
upgrades:
    - id: homestead
      name: Homestead
      block: 1150000
      features:
        - id: homestead # a feature configured in a code
    - id: gas-reprice
      name: Gas Reprice
      block: 2500000
      features:
        - id: set-gasprice
          options:
            gasprice: gastable2
    - id: diehard
      name: Die Hard
      block: 3000000
      features:
        - id: ecip1010 # bomb delay
          options:
            length: 2000000
        - id: set-gasprice
          options:
            gastprice: gastable3
        - id: eip155 # replay protection
          option:
            chain-id: 61
state:
  - address: 0x3282791d6fd713f1e94f4bfd565eaa78b3a0599d
    balance: "1337000000000000000000"
  - address: 0x17961d633bcf20a7b029a7d94b7df4da2ec5427f
    balance: "229427000000000000000"
bootstrap:
  - "45.32.7.81:30303"
  - "174.112.32.157:30303"
```

Configs for mainnet and testnet should be compiled into geth binary, but user should be able to specify custom config file from command line
